# SwiftLint configuration for TideGuard

# Exclude files or directories from linting
excluded:
  - Pods
  - Carthage
  - .build
  - Generated
  - Tests # Exclude unit tests if you don't want strict rules there

# Customize rule severity levels
opt_in_rules:
  - explicit_init
  - empty_count
  - first_where
  - multiline_parameters
  - private_action
  - missing_docs # Enforces documentation for public methods

disabled_rules:
  - force_cast # Avoids forced casting (use optional binding instead)
  - force_unwrapping # Avoids using '!'
  - line_length # Doesn't enforce strict line length (use common sense)
  - trailing_whitespace # Ignores trailing whitespaces to avoid unnecessary diffs

# Set thresholds
line_length:
  warning: 120
  error: 140

function_body_length:
  warning: 40
  error: 60

type_body_length:
  warning: 200
  error: 300

identifier_name:
  min_length: 3
  max_length: 40

# Enforce better practices
strong_iboutlet:
  severity: warning

# Customize indentation
indentation:
  character: space
  width: 4

# Enable SwiftLint rules for best practices
included:
  - TideGuard

